### ISSUE TITLE
服务器部署报错Fatal error

### ISSUE THREAD

**Issue by rebornkano** [cobub/razor#164]
Fatal error: 
Uncaught Error: [] operator not supported for strings in D:\02 apache_cobub\apache\Apache24\web\razor-master\web\system\core\Router.php:287 
Stack trace: 
#0 D:\02 apache_cobub\apache\Apache24\web\razor-master\web\system\core\Router.php(228): CI_Router->_validate_request(Array) 
#1 D:\02 apache_cobub\apache\Apache24\web\razor-master\web\system\core\Router.php(198): CI_Router->_set_request(Array) 
#2 D:\02 apache_cobub\apache\Apache24\web\razor-master\web\system\core\Router.php(161): CI_Router->_set_default_controller() 
#3 D:\02 apache_cobub\apache\Apache24\web\razor-master\web\system\core\CodeIgniter.php(174): CI_Router->_set_routing() 
#4 D:\02 apache_cobub\apache\Apache24\web\razor-master\web\index.php(202): require_once('D:\\02 apache_co...') 
#5 {main} thrown in D:\02 apache_cobub\apache\Apache24\web\razor-master\web\system\core\Router.php on line 287

不太熟悉php，apache服务器跑起来了，php配置好了，mysql服务启动了，还有什么地方需要修改呢，求教，感谢。

**Comment by a120476536** [comment]
用5.多的版本 太高了。这个hold不住
